import { Buffer } from "node:buffer"
import { createHash } from "node:crypto"
import { readFile } from "node:fs/promises"
import { basename, dirname, join, relative } from "node:path"
import satori from "satori"
import sharp from "sharp"
import { transformWithOxc, type Plugin, type ResolvedConfig } from "vite"
import { parseSatoriImage, satoriImagePattern } from "./satori.ts"

export function satoriImages(): Plugin {
  let config: ResolvedConfig
  const assets = new Map<string, Buffer>()
  const renders = new Map<string, Promise<string>>()

  function assetPath(fileName: string, routeFileName?: string): string {
    if (
      routeFileName !== undefined &&
      (config.base === "" || config.base.startsWith("."))
    ) {
      const path = relative(dirname(routeFileName), fileName).replaceAll(
        "\\",
        "/",
      )
      return path.startsWith(".") ? path : `./${path}`
    }
    const base =
      config.command === "serve"
        ? new URL(config.base, "http://solid-static.local").pathname
        : config.base
    return `${base}${fileName}`
  }

  async function replaceImages(
    html: string,
    loadFont: (src: string) => Promise<Buffer>,
    routeFileName?: string,
  ): Promise<string> {
    const matches = [...html.matchAll(satoriImagePattern)]
    const tokens = new Set(
      matches
        .map((match) => match.groups?.token)
        .filter((token): token is string => token !== undefined),
    )
    const images = await Promise.all(
      [...tokens].map(async (token) => {
        let operation = renders.get(token)
        if (operation === undefined) {
          const options = parseSatoriImage(token)
          operation = Promise.all(
            options.fonts.map(async (font) => ({
              name: font.name,
              data: await loadFont(font.src),
              weight: font.weight,
              style: font.style ?? ("normal" as const),
            })),
          ).then(async (fonts) => {
            const svg = await satori(options.element, {
              width: options.width,
              height: options.height,
              fonts,
            })
            const content = await sharp(Buffer.from(svg))
              .png()
              .withMetadata({
                exif: {
                  IFD0: {
                    ImageDescription:
                      "Generated by solid-static from a parameterized .satori.tsx template",
                  },
                },
              })
              .toBuffer()
            const hash = createHash("sha256")
              .update(content)
              .digest("hex")
              .slice(0, 16)
            const fileName = join(
              config.build.assetsDir,
              `social-${hash}.png`,
            ).replaceAll("\\", "/")
            assets.set(fileName, content)
            return fileName
          })
          renders.set(token, operation)
        }
        return [token, await operation] as const
      }),
    )
    const files = new Map(images)
    for (const match of matches) {
      const fileName = files.get(match.groups?.token ?? "")
      if (fileName === undefined)
        throw new TypeError("Missing rendered Satori image")
      const path = assetPath(fileName, routeFileName)
      const origin = match.groups?.origin
      const url =
        origin !== undefined && !/^https?:\/\//.test(path)
          ? new URL(path, `${origin}/${routeFileName ?? ""}`).toString()
          : path
      html = html.replaceAll(match[0], url)
    }
    return html
  }

  return {
    name: "solid-static-satori-images",
    enforce: "pre",
    buildStart() {
      renders.clear()
      assets.clear()
    },
    configResolved(resolved) {
      config = resolved
    },
    transform(code, id) {
      if (!id.split("?")[0]?.endsWith(".satori.tsx")) return undefined
      return transformWithOxc(code, id, {
        jsx: { runtime: "automatic", importSource: "satori/jsx" },
      })
    },
    configureServer(server) {
      server.watcher.on("change", () => {
        renders.clear()
        assets.clear()
      })
      server.middlewares.use(
        function satoriImageMiddleware(request, response, next) {
          const path = (request.url ?? "").split("?")[0]
          const content = [...assets].find(
            ([name]) => assetPath(name) === path,
          )?.[1]
          if (content === undefined) {
            next()
            return
          }
          response.setHeader("Content-Type", "image/png")
          response.end(request.method === "HEAD" ? undefined : content)
        },
      )
    },
    transformIndexHtml: {
      order: "post",
      handler(html) {
        return replaceImages(html, (src) => {
          const sourcePath = new URL(src, "http://solid-static.local").pathname
          const basePath = new URL(config.base, "http://solid-static.local")
            .pathname
          const pathname = decodeURIComponent(
            sourcePath.startsWith(basePath)
              ? `/${sourcePath.slice(basePath.length)}`
              : sourcePath,
          )
          const fileName = pathname.startsWith("/@fs/")
            ? pathname.slice("/@fs".length)
            : join(config.root, pathname)
          return readFile(fileName)
        })
      },
    },
    generateBundle: {
      order: "post",
      async handler(_options, bundle) {
        const fontFiles = new Set<string>()
        async function loadFont(src: string): Promise<Buffer> {
          const name = basename(
            decodeURIComponent(
              new URL(src, "http://solid-static.local").pathname,
            ),
          )
          const asset = Object.values(bundle).find(
            (output) =>
              output.type === "asset" && basename(output.fileName) === name,
          )
          if (asset?.type !== "asset")
            throw new TypeError(`Unable to find Satori font ${src}`)
          fontFiles.add(asset.fileName)
          return Buffer.from(asset.source)
        }
        for (const output of Object.values(bundle)) {
          if (output.type === "asset" && output.fileName.endsWith(".html"))
            output.source = await replaceImages(
              output.source.toString(),
              loadFont,
              output.fileName,
            )
        }
        for (const [fileName, content] of assets)
          this.emitFile({ type: "asset", fileName, source: content })
        for (const fileName of fontFiles) {
          const referenced = Object.values(bundle).some(
            (output) =>
              output.fileName !== fileName &&
              (output.type === "asset"
                ? output.source.toString()
                : output.code
              ).includes(fileName),
          )
          if (!referenced) delete bundle[fileName]
        }
      },
    },
  }
}
